import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface Translations {
  [key: string]: {
    fr: string;
    en: string;
  };
}

const translations: Translations = {
  // Navigation
  'nav.home': { fr: 'Accueil', en: 'Home' },
  'nav.features': { fr: 'Fonctionnalités', en: 'Features' },
  'nav.about': { fr: 'À propos', en: 'About' },
  'nav.contact': { fr: 'Contact', en: 'Contact' },
  'nav.login': { fr: 'Connexion', en: 'Login' },
  'nav.dashboard': { fr: 'Tableau de bord', en: 'Dashboard' },
  
  // Hero Section
  'hero.badge': { fr: 'Télépathologie IA', en: 'AI Telepathology' },
  'hero.title1': { fr: 'Diagnostic', en: 'Pathology' },
  'hero.title2': { fr: 'à Distance', en: 'Diagnosis' },
  'hero.title3': { fr: 'Intelligent', en: 'Reimagined' },
  'hero.subtitle': { 
    fr: 'Plateforme de télépathologie assistée par intelligence artificielle pour le cancer du sein et du col de l\'utérus. Conçue pour l\'Afrique, intégrée à PASS SANTÉ Mousso.', 
    en: 'AI-powered telepathology platform for breast and cervical cancer. Designed for Africa, integrated with PASS SANTÉ Mousso.' 
  },
  'hero.cta.start': { fr: 'Commencer', en: 'Get Started' },
  'hero.cta.demo': { fr: 'Voir la démo', en: 'Watch Demo' },
  
  // Stats
  'stats.centers': { fr: 'Centres connectés', en: 'Connected Centers' },
  'stats.cases': { fr: 'Cas analysés', en: 'Cases Analyzed' },
  'stats.pathologists': { fr: 'Pathologistes', en: 'Pathologists' },
  'stats.accuracy': { fr: 'Précision IA', en: 'AI Accuracy' },
  
  // Features
  'features.title': { fr: 'Fonctionnalités Clés', en: 'Key Features' },
  'features.subtitle': { fr: 'Une solution complète pour la télépathologie moderne', en: 'A complete solution for modern telepathology' },
  
  'features.capture.title': { fr: 'Capture d\'Images', en: 'Image Capture' },
  'features.capture.desc': { fr: 'Capture microscopique multi-zones avec compression adaptative et upload différé', en: 'Multi-zone microscopic capture with adaptive compression and deferred upload' },
  
  'features.analysis.title': { fr: 'Analyse IA', en: 'AI Analysis' },
  'features.analysis.desc': { fr: 'Assistance au diagnostic par intelligence artificielle pour une précision accrue', en: 'AI-assisted diagnosis for enhanced accuracy' },
  
  'features.collab.title': { fr: 'Collaboration', en: 'Collaboration' },
  'features.collab.desc': { fr: 'Second avis et consultation entre pathologistes en temps réel', en: 'Second opinions and real-time pathologist consultations' },
  
  'features.security.title': { fr: 'Sécurité', en: 'Security' },
  'features.security.desc': { fr: 'Chiffrement des données, authentification forte et audit complet', en: 'Data encryption, strong authentication and complete audit' },
  
  'features.integration.title': { fr: 'Intégration', en: 'Integration' },
  'features.integration.desc': { fr: 'Connecté nativement à PASS SANTÉ Mousso pour le suivi patient', en: 'Natively connected to PASS SANTÉ Mousso for patient tracking' },
  
  'features.offline.title': { fr: 'Mode Hors-ligne', en: 'Offline Mode' },
  'features.offline.desc': { fr: 'Sauvegarde automatique et reprise d\'analyse en cas de déconnexion', en: 'Auto-save and analysis resumption on disconnection' },
  
  // Pathologies
  'pathology.title': { fr: 'Pathologies Couvertes', en: 'Covered Pathologies' },
  'pathology.subtitle': { fr: 'Version 2 - Cancer du sein et du col de l\'utérus', en: 'Version 2 - Breast and cervical cancer' },
  'pathology.breast': { fr: 'Cancer du Sein', en: 'Breast Cancer' },
  'pathology.cervical': { fr: 'Cancer du Col', en: 'Cervical Cancer' },
  'pathology.breast.desc': { fr: 'Analyse histopathologique complète avec grading et biomarqueurs', en: 'Complete histopathological analysis with grading and biomarkers' },
  'pathology.cervical.desc': { fr: 'Dépistage et diagnostic avec classification Bethesda', en: 'Screening and diagnosis with Bethesda classification' },
  
  // User Profiles
  'profiles.title': { fr: 'Accès par Profil', en: 'Profile Access' },
  'profiles.subtitle': { fr: 'Tableaux de bord personnalisés pour chaque utilisateur', en: 'Personalized dashboards for each user' },
  'profiles.admin.title': { fr: 'Administrateur', en: 'Administrator' },
  'profiles.admin.desc': { fr: 'Gestion des centres, utilisateurs et statistiques globales', en: 'Center management, users and global statistics' },
  'profiles.pathologist.title': { fr: 'Pathologiste', en: 'Pathologist' },
  'profiles.pathologist.desc': { fr: 'Analyse des cas, annotations et validation des diagnostics', en: 'Case analysis, annotations and diagnosis validation' },
  'profiles.technician.title': { fr: 'Technicien', en: 'Lab Technician' },
  'profiles.technician.desc': { fr: 'Capture d\'images, création de cas et transmission', en: 'Image capture, case creation and transmission' },
  'profiles.clinician.title': { fr: 'Clinicien', en: 'Clinician' },
  'profiles.clinician.desc': { fr: 'Consultation des résultats via PASS SANTÉ Mousso', en: 'Results consultation via PASS SANTÉ Mousso' },
  
  // CTA Section
  'cta.title': { fr: 'Prêt à transformer vos diagnostics ?', en: 'Ready to transform your diagnostics?' },
  'cta.subtitle': { fr: 'Rejoignez les centres de santé qui utilisent KANYEH ASSIST', en: 'Join the health centers using KANYEH ASSIST' },
  'cta.button': { fr: 'Demander une démo', en: 'Request a Demo' },
  
  // Footer
  'footer.tagline': { fr: 'Télépathologie intelligente pour l\'Afrique', en: 'Intelligent telepathology for Africa' },
  'footer.product': { fr: 'Produit', en: 'Product' },
  'footer.company': { fr: 'Entreprise', en: 'Company' },
  'footer.legal': { fr: 'Légal', en: 'Legal' },
  'footer.privacy': { fr: 'Confidentialité', en: 'Privacy Policy' },
  'footer.terms': { fr: 'Conditions', en: 'Terms of Service' },
  'footer.copyright': { fr: '© 2025 INNOV\'KENEYA. Tous droits réservés.', en: '© 2025 INNOV\'KENEYA. All rights reserved.' },
  
  // Login
  'login.title': { fr: 'Connexion', en: 'Sign In' },
  'login.subtitle': { fr: 'Accédez à votre espace de travail', en: 'Access your workspace' },
  'login.selectRole': { fr: 'Sélectionnez votre profil pour continuer (mode démo)', en: 'Select your profile to continue (demo mode)' },
  'login.email': { fr: 'Email', en: 'Email' },
  'login.password': { fr: 'Mot de passe', en: 'Password' },
  'login.submit': { fr: 'Se connecter', en: 'Sign In' },
  'login.changeRole': { fr: 'Changer de profil', en: 'Change profile' },
  'login.demoNote': { fr: 'Mode démonstration - sélectionnez un profil pour explorer', en: 'Demo mode - select a profile to explore' },
  'login.role.system_admin': { fr: 'Administrateur Système', en: 'System Administrator' },
  'login.role.system_admin.desc': { fr: 'Gestion globale de la plateforme', en: 'Global platform management' },
  'login.role.center_admin': { fr: 'Administrateur Centre', en: 'Center Administrator' },
  'login.role.center_admin.desc': { fr: 'Gestion du centre de santé', en: 'Health center management' },
  'login.role.lab_technician': { fr: 'Technicien Laboratoire', en: 'Lab Technician' },
  'login.role.lab_technician.desc': { fr: 'Capture et transmission des cas', en: 'Case capture and transmission' },
  'login.role.pathologist': { fr: 'Pathologiste', en: 'Pathologist' },
  'login.role.pathologist.desc': { fr: 'Analyse et validation des diagnostics', en: 'Analysis and diagnosis validation' },
  'login.role.clinician': { fr: 'Médecin Clinicien', en: 'Clinician' },
  'login.role.clinician.desc': { fr: 'Consultation des résultats patients', en: 'Patient results consultation' },
  
  // Dashboard roles
  'dashboard.role.system_admin': { fr: 'Admin Système', en: 'System Admin' },
  'dashboard.role.center_admin': { fr: 'Admin Centre', en: 'Center Admin' },
  'dashboard.role.lab_technician': { fr: 'Technicien', en: 'Technician' },
  'dashboard.role.pathologist': { fr: 'Pathologiste', en: 'Pathologist' },
  'dashboard.role.clinician': { fr: 'Clinicien', en: 'Clinician' },
  
  // Sidebar
  'sidebar.menu': { fr: 'Menu', en: 'Menu' },
  'sidebar.dashboard': { fr: 'Tableau de bord', en: 'Dashboard' },
  'sidebar.centers': { fr: 'Centres', en: 'Centers' },
  'sidebar.users': { fr: 'Utilisateurs', en: 'Users' },
  'sidebar.statistics': { fr: 'Statistiques', en: 'Statistics' },
  'sidebar.audit': { fr: 'Audit', en: 'Audit' },
  'sidebar.system': { fr: 'Système', en: 'System' },
  'sidebar.settings': { fr: 'Paramètres', en: 'Settings' },
  'sidebar.team': { fr: 'Équipe', en: 'Team' },
  'sidebar.cases': { fr: 'Cas', en: 'Cases' },
  'sidebar.activity': { fr: 'Activité', en: 'Activity' },
  'sidebar.newCase': { fr: 'Nouveau cas', en: 'New Case' },
  'sidebar.myCases': { fr: 'Mes cas', en: 'My Cases' },
  'sidebar.pending': { fr: 'En attente', en: 'Pending' },
  'sidebar.toAnalyze': { fr: 'À analyser', en: 'To Analyze' },
  'sidebar.myAnalyses': { fr: 'Mes analyses', en: 'My Analyses' },
  'sidebar.secondOpinion': { fr: 'Second avis', en: 'Second Opinion' },
  'sidebar.reports': { fr: 'Rapports', en: 'Reports' },
  'sidebar.myPatients': { fr: 'Mes patients', en: 'My Patients' },
  'sidebar.results': { fr: 'Résultats', en: 'Results' },
  'sidebar.connectedCenter': { fr: 'Centre connecté', en: 'Connected center' },
  
  // Stats
  'stats.totalCenters': { fr: 'Centres totaux', en: 'Total Centers' },
  'stats.activeUsers': { fr: 'Utilisateurs actifs', en: 'Active Users' },
  'stats.totalCases': { fr: 'Cas totaux', en: 'Total Cases' },
  'stats.avgResponseTime': { fr: 'Temps moyen', en: 'Avg Response Time' },
  'stats.thisMonth': { fr: 'ce mois', en: 'this month' },
  'stats.improvement': { fr: 'amélioration', en: 'improvement' },
  'stats.teamMembers': { fr: 'Membres équipe', en: 'Team Members' },
  'stats.casesToday': { fr: 'Cas aujourd\'hui', en: 'Cases Today' },
  'stats.pendingAnalysis': { fr: 'En attente d\'analyse', en: 'Pending Analysis' },
  'stats.completedThisWeek': { fr: 'Complétés cette semaine', en: 'Completed This Week' },
  'stats.vsYesterday': { fr: 'vs hier', en: 'vs yesterday' },
  'stats.vsLastWeek': { fr: 'vs semaine dernière', en: 'vs last week' },
  'stats.casesLabel': { fr: 'cas', en: 'cases' },
  'stats.breastCancer': { fr: 'Cancer du sein', en: 'Breast Cancer' },
  'stats.cervicalCancer': { fr: 'Cancer du col', en: 'Cervical Cancer' },
  'stats.validationRate': { fr: 'Taux de validation', en: 'Validation Rate' },
  'stats.avgTurnaround': { fr: 'Délai moyen', en: 'Avg Turnaround' },
  'stats.sentForAnalysis': { fr: 'Envoyés pour analyse', en: 'Sent for Analysis' },
  'stats.drafts': { fr: 'Brouillons', en: 'Drafts' },
  'stats.validated': { fr: 'Validés', en: 'Validated' },
  'stats.thisWeek': { fr: 'cette semaine', en: 'this week' },
  'stats.toAnalyze': { fr: 'À analyser', en: 'To Analyze' },
  'stats.analyzedToday': { fr: 'Analysés aujourd\'hui', en: 'Analyzed Today' },
  'stats.avgAnalysisTime': { fr: 'Temps moyen analyse', en: 'Avg Analysis Time' },
  'stats.secondOpinions': { fr: 'Seconds avis', en: 'Second Opinions' },
  'stats.faster': { fr: 'plus rapide', en: 'faster' },
  'stats.myPatients': { fr: 'Mes patients', en: 'My Patients' },
  'stats.resultsAvailable': { fr: 'Résultats disponibles', en: 'Results Available' },
  'stats.awaitingResults': { fr: 'En attente résultats', en: 'Awaiting Results' },
  'stats.avgWaitTime': { fr: 'Temps d\'attente moyen', en: 'Avg Wait Time' },
  'stats.patients': { fr: 'patients', en: 'patients' },
  
  // Status
  'status.draft': { fr: 'Brouillon', en: 'Draft' },
  'status.pending': { fr: 'En attente', en: 'Pending' },
  'status.analyzing': { fr: 'En analyse', en: 'Analyzing' },
  'status.validated': { fr: 'Validé', en: 'Validated' },
  'status.archived': { fr: 'Archivé', en: 'Archived' },
  
  // Table
  'table.caseId': { fr: 'ID Cas', en: 'Case ID' },
  'table.patient': { fr: 'Patient', en: 'Patient' },
  'table.pathology': { fr: 'Pathologie', en: 'Pathology' },
  'table.center': { fr: 'Centre', en: 'Center' },
  'table.status': { fr: 'Statut', en: 'Status' },
  'table.date': { fr: 'Date', en: 'Date' },
  
  // Actions
  'action.newCase': { fr: 'Nouveau cas', en: 'New Case' },
  'action.uploadImages': { fr: 'Télécharger images', en: 'Upload Images' },
  'action.continueDraft': { fr: 'Continuer brouillon', en: 'Continue Draft' },
  'action.createNewCase': { fr: 'Créer un nouveau cas', en: 'Create New Case' },
  'action.viewAll': { fr: 'Voir tout', en: 'View All' },
  'action.review': { fr: 'Examiner', en: 'Review' },
  'action.viewReport': { fr: 'Voir rapport', en: 'View Report' },
  'action.openPassSante': { fr: 'Ouvrir PASS SANTÉ', en: 'Open PASS SANTÉ' },
  
  // Priority
  'priority.urgent': { fr: 'Urgent', en: 'Urgent' },
  
  // Dashboard titles
  'dashboard.admin.welcome': { fr: 'Vue d\'ensemble système', en: 'System Overview' },
  'dashboard.admin.subtitle': { fr: 'Statistiques globales de la plateforme', en: 'Global platform statistics' },
  'dashboard.admin.casesTrend': { fr: 'Tendance des cas', en: 'Cases Trend' },
  'dashboard.admin.centerDistribution': { fr: 'Distribution par centre', en: 'Center Distribution' },
  'dashboard.admin.recentCases': { fr: 'Cas récents (tous centres)', en: 'Recent Cases (all centers)' },
  'dashboard.centerAdmin.welcome': { fr: 'Tableau de bord Centre', en: 'Center Dashboard' },
  'dashboard.centerAdmin.subtitle': { fr: 'Vue d\'ensemble de votre centre', en: 'Your center overview' },
  'dashboard.centerAdmin.teamActivity': { fr: 'Activité équipe', en: 'Team Activity' },
  'dashboard.centerAdmin.performance': { fr: 'Performance', en: 'Performance' },
  'dashboard.centerAdmin.recentCases': { fr: 'Cas récents', en: 'Recent Cases' },
  'dashboard.centerAdmin.pendingAlert': { fr: '3 cas en attente > 24h', en: '3 cases pending > 24h' },
  'dashboard.technician.welcome': { fr: 'Bienvenue', en: 'Welcome' },
  'dashboard.technician.myCases': { fr: 'Mes cas', en: 'My Cases' },
  'dashboard.technician.workflowStatus': { fr: 'État du flux', en: 'Workflow Status' },
  'dashboard.pathologist.welcome': { fr: 'Bienvenue', en: 'Welcome' },
  'dashboard.pathologist.subtitle': { fr: 'Cas en attente de votre analyse', en: 'Cases awaiting your analysis' },
  'dashboard.pathologist.urgentCases': { fr: 'Cas urgents', en: 'Urgent cases' },
  'dashboard.pathologist.casesToAnalyze': { fr: 'Cas à analyser', en: 'Cases to Analyze' },
  'dashboard.pathologist.secondOpinions': { fr: 'Demandes de second avis', en: 'Second Opinion Requests' },
  'dashboard.pathologist.requestFrom': { fr: 'Demande de', en: 'Request from' },
  'dashboard.pathologist.recentAnalyses': { fr: 'Analyses récentes', en: 'Recent Analyses' },
  'dashboard.clinician.welcome': { fr: 'Bienvenue', en: 'Welcome' },
  'dashboard.clinician.subtitle': { fr: 'Suivi de vos patients en télépathologie', en: 'Your telepathology patients follow-up' },
  'dashboard.clinician.myPatients': { fr: 'Mes patients', en: 'My Patients' },
  'dashboard.clinician.passSanteIntegration': { fr: 'Intégration PASS SANTÉ Mousso', en: 'PASS SANTÉ Mousso Integration' },
  'dashboard.clinician.passSanteDesc': { fr: 'Résultats automatiquement synchronisés avec le DMP', en: 'Results automatically synced with EMR' },
  'dashboard.clinician.waitingForAnalysis': { fr: 'En attente d\'analyse', en: 'Waiting for analysis' },
  'dashboard.clinician.responseTime': { fr: 'Temps de réponse', en: 'Response Time' },
  'dashboard.clinician.pathologyDistribution': { fr: 'Répartition pathologies', en: 'Pathology Distribution' },
  'dashboard.chartPlaceholder': { fr: 'Graphique (à implémenter)', en: 'Chart (to implement)' },
  'dashboard.mapPlaceholder': { fr: 'Carte (à implémenter)', en: 'Map (to implement)' },
  
  // AI Analysis
  'ai.analysisTitle': { fr: 'Analyse IA', en: 'AI Analysis' },
  'ai.analysisDescription': { fr: 'L\'IA va analyser l\'image pour détecter les régions suspectes', en: 'AI will analyze the image to detect suspicious regions' },
  'ai.startAnalysis': { fr: 'Lancer l\'analyse', en: 'Start Analysis' },
  'ai.analyzing': { fr: 'Analyse en cours...', en: 'Analyzing...' },
  'ai.detectingRegions': { fr: 'Détection des régions d\'intérêt...', en: 'Detecting regions of interest...' },
  'ai.analysisComplete': { fr: 'Analyse terminée', en: 'Analysis Complete' },
  'ai.regionsDetected': { fr: 'Régions détectées', en: 'Regions Detected' },
  'ai.confidence': { fr: 'confiance', en: 'confidence' },
  'ai.malignant': { fr: 'Malin', en: 'Malignant' },
  'ai.suspicious': { fr: 'Suspect', en: 'Suspicious' },
  'ai.benign': { fr: 'Bénin', en: 'Benign' },
  'ai.reviewRequired': { fr: 'Vérification requise', en: 'Review Required' },
  'ai.reviewDescription': { fr: 'Des zones suspectes ont été détectées. Veuillez les examiner.', en: 'Suspicious areas detected. Please review them.' },
  'ai.reanalyze': { fr: 'Relancer l\'analyse', en: 'Re-analyze' },
  
  // AI Assistant Chat
  'ai.assistantTitle': { fr: 'Assistant IA', en: 'AI Assistant' },
  'ai.chatWelcome': { fr: 'Posez vos questions sur le diagnostic ou les recommandations', en: 'Ask your questions about diagnosis or recommendations' },
  'ai.chatPlaceholder': { fr: 'Posez une question...', en: 'Ask a question...' },
  
  // Quality Check
  'quality.title': { fr: 'Contrôle Qualité IA', en: 'AI Quality Control' },
  'quality.description': { fr: 'Vérifiez la qualité de l\'image avant transmission', en: 'Check image quality before transmission' },
  'quality.checkButton': { fr: 'Vérifier la qualité', en: 'Check Quality' },
  'quality.checking': { fr: 'Vérification en cours...', en: 'Checking quality...' },
  'quality.sharpness': { fr: 'Netteté', en: 'Sharpness' },
  'quality.sharpnessGood': { fr: 'Image nette et bien définie', en: 'Image is sharp and well-defined' },
  'quality.lighting': { fr: 'Éclairage', en: 'Lighting' },
  'quality.lightingGood': { fr: 'Éclairage uniforme et adéquat', en: 'Uniform and adequate lighting' },
  'quality.focus': { fr: 'Mise au point', en: 'Focus' },
  'quality.focusWarning': { fr: 'Légère perte de mise au point sur les bords', en: 'Slight focus loss on edges' },
  'quality.contrast': { fr: 'Contraste', en: 'Contrast' },
  'quality.contrastGood': { fr: 'Bon contraste entre les structures', en: 'Good contrast between structures' },
  'quality.artifacts': { fr: 'Artefacts', en: 'Artifacts' },
  'quality.artifactsGood': { fr: 'Aucun artefact détecté', en: 'No artifacts detected' },
  'quality.excellent': { fr: 'Excellente', en: 'Excellent' },
  'quality.acceptable': { fr: 'Acceptable', en: 'Acceptable' },
  'quality.insufficient': { fr: 'Insuffisante', en: 'Insufficient' },
  'quality.recommendations': { fr: 'Recommandations', en: 'Recommendations' },
  'quality.recheckButton': { fr: 'Revérifier', en: 'Re-check' },

  // Case Creation
  'case.createTitle': { fr: 'Créer un nouveau cas', en: 'Create New Case' },
  'case.stepPatient': { fr: 'Patient', en: 'Patient' },
  'case.stepCase': { fr: 'Cas', en: 'Case' },
  'case.stepImages': { fr: 'Images', en: 'Images' },
  'case.stepReview': { fr: 'Révision', en: 'Review' },
  'case.lastName': { fr: 'Nom', en: 'Last Name' },
  'case.firstName': { fr: 'Prénom', en: 'First Name' },
  'case.dateOfBirth': { fr: 'Date de naissance', en: 'Date of Birth' },
  'case.gender': { fr: 'Genre', en: 'Gender' },
  'case.female': { fr: 'Femme', en: 'Female' },
  'case.male': { fr: 'Homme', en: 'Male' },
  'case.phone': { fr: 'Téléphone', en: 'Phone' },
  'case.cmuNumber': { fr: 'N° CMU', en: 'CMU Number' },
  'case.pathology': { fr: 'Pathologie', en: 'Pathology' },
  'case.sampleType': { fr: 'Type d\'échantillon', en: 'Sample Type' },
  'case.selectSampleType': { fr: 'Sélectionner le type', en: 'Select type' },
  'case.collectionDate': { fr: 'Date de prélèvement', en: 'Collection Date' },
  'case.priority': { fr: 'Priorité', en: 'Priority' },
  'case.priorityNormal': { fr: 'Normal', en: 'Normal' },
  'case.priorityHigh': { fr: 'Élevée', en: 'High' },
  'case.priorityUrgent': { fr: 'Urgent', en: 'Urgent' },
  'case.clinicalNotes': { fr: 'Notes cliniques', en: 'Clinical Notes' },
  'case.clinicalNotesPlaceholder': { fr: 'Symptômes, observations, antécédents pertinents...', en: 'Symptoms, observations, relevant history...' },
  'case.dragDropImages': { fr: 'Glissez-déposez vos images ici', en: 'Drag and drop your images here' },
  'case.supportedFormats': { fr: 'JPG, PNG, TIFF jusqu\'à 50 Mo', en: 'JPG, PNG, TIFF up to 50 MB' },
  'case.selectFiles': { fr: 'Sélectionner des fichiers', en: 'Select Files' },
  'case.uploading': { fr: 'Téléchargement', en: 'Uploading' },
  'case.uploadedImages': { fr: 'Images téléchargées', en: 'Uploaded Images' },
  'case.imagesUploaded': { fr: 'Images téléchargées avec succès', en: 'Images uploaded successfully' },
  'case.noImagesWarning': { fr: 'Aucune image ajoutée. Un cas nécessite au moins une image.', en: 'No images added. A case requires at least one image.' },
  'case.patientInfo': { fr: 'Informations patient', en: 'Patient Information' },
  'case.caseInfo': { fr: 'Informations du cas', en: 'Case Information' },
  'case.born': { fr: 'Né(e) le', en: 'Born' },
  'case.images': { fr: 'Images', en: 'Images' },
  'case.imagesAttached': { fr: 'image(s) attachée(s)', en: 'image(s) attached' },
  'case.savedAsDraft': { fr: 'Cas enregistré comme brouillon', en: 'Case saved as draft' },
  'case.submittedForAnalysis': { fr: 'Cas envoyé pour analyse', en: 'Case submitted for analysis' },
  'action.cancel': { fr: 'Annuler', en: 'Cancel' },
  'action.previous': { fr: 'Précédent', en: 'Previous' },
  'action.next': { fr: 'Suivant', en: 'Next' },
  'action.saveDraft': { fr: 'Enregistrer brouillon', en: 'Save Draft' },
  'action.submitForAnalysis': { fr: 'Envoyer pour analyse', en: 'Submit for Analysis' },
  'action.close': { fr: 'Fermer', en: 'Close' },

  // My Cases Page
  'myCases.total': { fr: 'Total', en: 'Total' },
  'myCases.searchPlaceholder': { fr: 'Rechercher par ID, nom de patient...', en: 'Search by ID, patient name...' },
  'myCases.filterStatus': { fr: 'Statut', en: 'Status' },
  'myCases.filterPathology': { fr: 'Pathologie', en: 'Pathology' },
  'myCases.filterDate': { fr: 'Date', en: 'Date' },
  'myCases.allStatus': { fr: 'Tous les statuts', en: 'All statuses' },
  'myCases.allPathologies': { fr: 'Toutes', en: 'All' },
  'myCases.allDates': { fr: 'Toutes les dates', en: 'All dates' },
  'myCases.today': { fr: 'Aujourd\'hui', en: 'Today' },
  'myCases.thisWeek': { fr: 'Cette semaine', en: 'This week' },
  'myCases.thisMonth': { fr: 'Ce mois', en: 'This month' },
  'myCases.clearFilters': { fr: 'Effacer les filtres', en: 'Clear filters' },
  'myCases.casesFound': { fr: 'cas trouvé(s)', en: 'case(s) found' },
  'myCases.refresh': { fr: 'Actualiser', en: 'Refresh' },
  'myCases.noCases': { fr: 'Aucun cas trouvé', en: 'No cases found' },
  'myCases.noCasesDescription': { fr: 'Créez votre premier cas pour commencer.', en: 'Create your first case to get started.' },
  'myCases.actions': { fr: 'Actions', en: 'Actions' },
  'myCases.view': { fr: 'Voir', en: 'View' },
  'myCases.edit': { fr: 'Modifier', en: 'Edit' },
  'myCases.submit': { fr: 'Envoyer', en: 'Submit' },
  'myCases.delete': { fr: 'Supprimer', en: 'Delete' },
  'myCases.confirmDelete': { fr: 'Confirmer la suppression', en: 'Confirm deletion' },
  'myCases.deleteWarning': { fr: 'Êtes-vous sûr de vouloir supprimer ce cas ?', en: 'Are you sure you want to delete this case?' },
  'myCases.caseDetails': { fr: 'Détails du cas', en: 'Case Details' },
  'myCases.createdAt': { fr: 'Créé le', en: 'Created at' },

  // Pending Cases Page
  'pending.title': { fr: 'En attente', en: 'Pending' },
  'pending.subtitle': { fr: 'Suivez vos cas en cours d\'analyse', en: 'Track your cases being analyzed' },
  'pending.waitingAssignment': { fr: 'En attente d\'attribution', en: 'Waiting for assignment' },
  'pending.inAnalysis': { fr: 'En cours d\'analyse', en: 'Being analyzed' },
  'pending.urgentCases': { fr: 'Cas urgents', en: 'Urgent cases' },
  'pending.allPending': { fr: 'Tous les cas en attente', en: 'All pending cases' },
  'pending.waitingForAssignment': { fr: 'En attente d\'un pathologiste', en: 'Waiting for a pathologist' },
  'pending.beingAnalyzed': { fr: 'Analyse en cours par un pathologiste', en: 'Being analyzed by a pathologist' },
  'pending.noPendingCases': { fr: 'Aucun cas en attente', en: 'No pending cases' },
  'pending.noPendingDescription': { fr: 'Tous vos cas ont été traités.', en: 'All your cases have been processed.' },
  'pending.submittedOn': { fr: 'Envoyé le', en: 'Submitted on' },
  'pending.waitTime': { fr: 'Temps d\'attente', en: 'Wait time' },
  'pending.estimated': { fr: 'Estimation', en: 'Estimated' },
  'pending.estimatedRemaining': { fr: 'Temps restant estimé', en: 'Estimated remaining' },
  'pending.progress': { fr: 'Progression', en: 'Progress' },
  'pending.trackingCase': { fr: 'Suivi du cas', en: 'Case Tracking' },
  'pending.timeline': { fr: 'Chronologie', en: 'Timeline' },
  'pending.stepCreated': { fr: 'Cas créé', en: 'Case created' },
  'pending.stepSubmitted': { fr: 'Envoyé pour analyse', en: 'Submitted for analysis' },
  'pending.stepAssigned': { fr: 'Attribué à un pathologiste', en: 'Assigned to pathologist' },
  'pending.stepAnalyzing': { fr: 'Analyse en cours', en: 'Analysis in progress' },
  'pending.stepValidated': { fr: 'Validé', en: 'Validated' },

  // To Analyze Page
  'dashboard.toAnalyze.title': { fr: 'À analyser', en: 'To Analyze' },
  'dashboard.toAnalyze.subtitle': { fr: 'Cas en attente de votre analyse', en: 'Cases awaiting your analysis' },
  'dashboard.toAnalyze.urgentCases': { fr: 'cas urgent(s)', en: 'urgent case(s)' },
  'dashboard.toAnalyze.totalPending': { fr: 'Total en attente', en: 'Total Pending' },
  'dashboard.toAnalyze.urgentPriority': { fr: 'Priorité haute/urgente', en: 'High/Urgent Priority' },
  'dashboard.toAnalyze.inProgress': { fr: 'En cours d\'analyse', en: 'In Progress' },
  'dashboard.toAnalyze.avgWaitTime': { fr: 'Temps d\'attente moyen', en: 'Avg Wait Time' },
  'dashboard.toAnalyze.searchPlaceholder': { fr: 'Rechercher par ID, nom de patient...', en: 'Search by ID, patient name...' },
  'dashboard.toAnalyze.casesList': { fr: 'Liste des cas', en: 'Cases List' },
  'dashboard.toAnalyze.caseDetails': { fr: 'Détails du cas', en: 'Case Details' },
  'dashboard.toAnalyze.analysisMode': { fr: 'Mode analyse', en: 'Analysis Mode' },
  'dashboard.toAnalyze.image': { fr: 'Image', en: 'Image' },
  'dashboard.toAnalyze.imagePlaceholder': { fr: 'Image du prélèvement', en: 'Sample Image' },
  'dashboard.toAnalyze.slideImage': { fr: 'Lame', en: 'Slide' },
  'dashboard.toAnalyze.diagnosis': { fr: 'Diagnostic', en: 'Diagnosis' },
  'dashboard.toAnalyze.classification': { fr: 'Classification', en: 'Classification' },
  'dashboard.toAnalyze.selectDiagnosis': { fr: 'Sélectionner un diagnostic', en: 'Select a diagnosis' },
  'dashboard.toAnalyze.analysisNotes': { fr: 'Notes d\'analyse', en: 'Analysis Notes' },
  'dashboard.toAnalyze.notesPlaceholder': { fr: 'Observations, commentaires, recommandations...', en: 'Observations, comments, recommendations...' },
  'filter.pathology': { fr: 'Pathologie', en: 'Pathology' },
  'filter.allPathologies': { fr: 'Toutes les pathologies', en: 'All pathologies' },
  'filter.priority': { fr: 'Priorité', en: 'Priority' },
  'filter.allPriorities': { fr: 'Toutes les priorités', en: 'All priorities' },
  'priority.high': { fr: 'Haute', en: 'High' },
  'priority.normal': { fr: 'Normale', en: 'Normal' },
  'table.submittedBy': { fr: 'Soumis par', en: 'Submitted By' },
  'table.submittedAt': { fr: 'Date soumission', en: 'Submitted At' },
  'table.waitTime': { fr: 'Attente', en: 'Wait Time' },
  'table.images': { fr: 'Images', en: 'Images' },
  'table.actions': { fr: 'Actions', en: 'Actions' },
  'action.analyze': { fr: 'Analyser', en: 'Analyze' },
  'action.startAnalysis': { fr: 'Commencer l\'analyse', en: 'Start Analysis' },
  'action.submitAnalysis': { fr: 'Soumettre l\'analyse', en: 'Submit Analysis' },
  'action.saveAndClose': { fr: 'Sauvegarder et fermer', en: 'Save and Close' },
  'action.requestSecondOpinion': { fr: 'Demander un second avis', en: 'Request Second Opinion' },
  'diagnosis.normal': { fr: 'Normal', en: 'Normal' },
  'diagnosis.benign': { fr: 'Bénin', en: 'Benign' },
  'diagnosis.atypical': { fr: 'Atypique', en: 'Atypical' },
  'diagnosis.suspicious': { fr: 'Suspect', en: 'Suspicious' },
  'diagnosis.malignant': { fr: 'Malin', en: 'Malignant' },

  // My Analyses Page
  'myAnalyses.title': { fr: 'Mes analyses', en: 'My Analyses' },
  'myAnalyses.subtitle': { fr: 'Historique de vos analyses avec statistiques de performance', en: 'Your analysis history with performance statistics' },
  'myAnalyses.exportReport': { fr: 'Exporter rapport', en: 'Export Report' },
  'myAnalyses.totalAnalyses': { fr: 'Total analyses', en: 'Total Analyses' },
  'myAnalyses.analyzedToday': { fr: 'Analysés aujourd\'hui', en: 'Analyzed Today' },
  'myAnalyses.avgTime': { fr: 'Temps moyen', en: 'Avg Time' },
  'myAnalyses.secondOpinions': { fr: 'Seconds avis', en: 'Second Opinions' },
  'myAnalyses.listTab': { fr: 'Liste', en: 'List' },
  'myAnalyses.statsTab': { fr: 'Statistiques', en: 'Statistics' },
  'myAnalyses.searchPlaceholder': { fr: 'Rechercher par ID, nom de patient...', en: 'Search by ID, patient name...' },
  'myAnalyses.filterDiagnosis': { fr: 'Diagnostic', en: 'Diagnosis' },
  'myAnalyses.allDiagnoses': { fr: 'Tous les diagnostics', en: 'All diagnoses' },
  'myAnalyses.filterPeriod': { fr: 'Période', en: 'Period' },
  'myAnalyses.allPeriods': { fr: 'Toutes les périodes', en: 'All periods' },
  'myAnalyses.analysesHistory': { fr: 'Historique des analyses', en: 'Analysis History' },
  'myAnalyses.diagnosis': { fr: 'Diagnostic', en: 'Diagnosis' },
  'myAnalyses.analyzedAt': { fr: 'Date analyse', en: 'Analyzed At' },
  'myAnalyses.duration': { fr: 'Durée', en: 'Duration' },
  'myAnalyses.tools': { fr: 'Outils', en: 'Tools' },
  'myAnalyses.evolutionChart': { fr: 'Évolution des analyses', en: 'Analysis Evolution' },
  'myAnalyses.analysesCount': { fr: 'Nombre d\'analyses', en: 'Analysis Count' },
  'myAnalyses.avgTimeMin': { fr: 'Temps moyen (min)', en: 'Avg Time (min)' },
  'myAnalyses.diagnosisDistribution': { fr: 'Répartition des diagnostics', en: 'Diagnosis Distribution' },
  'myAnalyses.weeklyActivity': { fr: 'Activité hebdomadaire', en: 'Weekly Activity' },
  'myAnalyses.performanceSummary': { fr: 'Résumé de performance', en: 'Performance Summary' },
  'myAnalyses.thisMonthTotal': { fr: 'Ce mois', en: 'This Month' },
  'myAnalyses.avgAnalysisTime': { fr: 'Temps moyen analyse', en: 'Avg Analysis Time' },
  'myAnalyses.aiAgreementRate': { fr: 'Accord avec IA', en: 'AI Agreement Rate' },
  'myAnalyses.secondOpinionsGiven': { fr: 'Seconds avis donnés', en: 'Second Opinions Given' },
  'myAnalyses.analysisDetails': { fr: 'Détails de l\'analyse', en: 'Analysis Details' },
  'myAnalyses.notes': { fr: 'Notes d\'analyse', en: 'Analysis Notes' },
  'myAnalyses.downloadReport': { fr: 'Télécharger rapport', en: 'Download Report' },

  // Second Opinion Page
  'secondOpinion.title': { fr: 'Second avis', en: 'Second Opinion' },
  'secondOpinion.subtitle': { fr: 'Gérez les demandes et réponses de second avis', en: 'Manage second opinion requests and responses' },
  'secondOpinion.pendingRequests': { fr: 'demande(s) en attente', en: 'pending request(s)' },
  'secondOpinion.receivedPending': { fr: 'Reçues en attente', en: 'Received Pending' },
  'secondOpinion.inReview': { fr: 'En cours d\'examen', en: 'In Review' },
  'secondOpinion.completed': { fr: 'Complétées', en: 'Completed' },
  'secondOpinion.sentPending': { fr: 'Envoyées en attente', en: 'Sent Pending' },
  'secondOpinion.receivedTab': { fr: 'Demandes reçues', en: 'Received Requests' },
  'secondOpinion.sentTab': { fr: 'Demandes envoyées', en: 'Sent Requests' },
  'secondOpinion.searchPlaceholder': { fr: 'Rechercher par ID, patient, pathologiste...', en: 'Search by ID, patient, pathologist...' },
  'secondOpinion.filterStatus': { fr: 'Statut', en: 'Status' },
  'secondOpinion.allStatuses': { fr: 'Tous les statuts', en: 'All statuses' },
  'secondOpinion.statusPending': { fr: 'En attente', en: 'Pending' },
  'secondOpinion.statusInReview': { fr: 'En examen', en: 'In Review' },
  'secondOpinion.statusCompleted': { fr: 'Complété', en: 'Completed' },
  'secondOpinion.receivedRequests': { fr: 'Demandes reçues', en: 'Received Requests' },
  'secondOpinion.sentRequests': { fr: 'Demandes envoyées', en: 'Sent Requests' },
  'secondOpinion.noRequests': { fr: 'Aucune demande de second avis', en: 'No second opinion requests' },
  'secondOpinion.noSentRequests': { fr: 'Aucune demande envoyée', en: 'No sent requests' },
  'secondOpinion.initialDiagnosis': { fr: 'Diagnostic initial', en: 'Initial Diagnosis' },
  'secondOpinion.reason': { fr: 'Motif de la demande', en: 'Request Reason' },
  'secondOpinion.yourResponse': { fr: 'Votre réponse', en: 'Your Response' },
  'secondOpinion.respondedAt': { fr: 'Répondu le', en: 'Responded at' },
  'secondOpinion.startReview': { fr: 'Examiner', en: 'Review' },
  'secondOpinion.continueReview': { fr: 'Continuer', en: 'Continue' },
  'secondOpinion.sentTo': { fr: 'Envoyé à', en: 'Sent to' },
  'secondOpinion.yourDiagnosis': { fr: 'Votre diagnostic', en: 'Your Diagnosis' },
  'secondOpinion.responseReceived': { fr: 'Réponse reçue', en: 'Response Received' },
  'secondOpinion.provideOpinion': { fr: 'Donner votre avis', en: 'Provide Opinion' },
  'secondOpinion.requestedBy': { fr: 'Demandé par', en: 'Requested by' },
  'secondOpinion.yourDiagnosisLabel': { fr: 'Votre diagnostic', en: 'Your Diagnosis' },
  'secondOpinion.selectDiagnosis': { fr: 'Sélectionner votre conclusion', en: 'Select your conclusion' },
  'secondOpinion.confirmDiagnosis': { fr: 'Confirme le diagnostic initial', en: 'Confirm initial diagnosis' },
  'secondOpinion.modifyDiagnosis': { fr: 'Modifie le diagnostic', en: 'Modify diagnosis' },
  'secondOpinion.disagreeDiagnosis': { fr: 'Désaccord avec le diagnostic', en: 'Disagree with diagnosis' },
  'secondOpinion.inconclusiveDiagnosis': { fr: 'Non concluant - examens supplémentaires', en: 'Inconclusive - further tests needed' },
  'secondOpinion.detailedOpinion': { fr: 'Opinion détaillée', en: 'Detailed Opinion' },
  'secondOpinion.opinionPlaceholder': { fr: 'Décrivez votre analyse, vos observations et recommandations...', en: 'Describe your analysis, observations and recommendations...' },
  'secondOpinion.submitOpinion': { fr: 'Soumettre l\'avis', en: 'Submit Opinion' },
  'secondOpinion.requestDetails': { fr: 'Détails de la demande', en: 'Request Details' },
  'action.view': { fr: 'Voir', en: 'View' },

  // Reports Page
  'reports.title': { fr: 'Rapports', en: 'Reports' },
  'reports.subtitle': { fr: 'Générez et consultez les rapports d\'activité', en: 'Generate and view activity reports' },
  'reports.generateNew': { fr: 'Générer un rapport', en: 'Generate Report' },
  'reports.totalReports': { fr: 'Total rapports', en: 'Total Reports' },
  'reports.readyToDownload': { fr: 'Prêts à télécharger', en: 'Ready to Download' },
  'reports.generating': { fr: 'En génération', en: 'Generating' },
  'reports.thisMonth': { fr: 'Ce mois', en: 'This Month' },
  'reports.dashboardTab': { fr: 'Tableau de bord', en: 'Dashboard' },
  'reports.reportsTab': { fr: 'Rapports', en: 'Reports' },
  'reports.activityTrend': { fr: 'Tendance d\'activité', en: 'Activity Trend' },
  'reports.casesCreated': { fr: 'Cas créés', en: 'Cases Created' },
  'reports.casesAnalyzed': { fr: 'Cas analysés', en: 'Cases Analyzed' },
  'reports.casesValidated': { fr: 'Cas validés', en: 'Cases Validated' },
  'reports.diagnosisDistribution': { fr: 'Répartition des diagnostics', en: 'Diagnosis Distribution' },
  'reports.centerPerformance': { fr: 'Performance par centre', en: 'Center Performance' },
  'reports.totalCases': { fr: 'Total cas', en: 'Total Cases' },
  'reports.validationRate': { fr: 'Taux validation (%)', en: 'Validation Rate (%)' },
  'reports.totalCasesYear': { fr: 'Cas total année', en: 'Total Cases Year' },
  'reports.avgAnalysisTime': { fr: 'Temps analyse moyen', en: 'Avg Analysis Time' },
  'reports.activePathologists': { fr: 'Pathologistes actifs', en: 'Active Pathologists' },
  'reports.filterType': { fr: 'Type', en: 'Type' },
  'reports.allTypes': { fr: 'Tous les types', en: 'All types' },
  'reports.typeActivity': { fr: 'Activité', en: 'Activity' },
  'reports.typePerformance': { fr: 'Performance', en: 'Performance' },
  'reports.typeDiagnostic': { fr: 'Diagnostic', en: 'Diagnostic' },
  'reports.typeCustom': { fr: 'Personnalisé', en: 'Custom' },
  'reports.filterPeriod': { fr: 'Période', en: 'Period' },
  'reports.allPeriods': { fr: 'Toutes les périodes', en: 'All periods' },
  'reports.thisWeek': { fr: 'Cette semaine', en: 'This Week' },
  'reports.thisQuarter': { fr: 'Ce trimestre', en: 'This Quarter' },
  'reports.thisYear': { fr: 'Cette année', en: 'This Year' },
  'reports.statusReady': { fr: 'Prêt', en: 'Ready' },
  'reports.statusGenerating': { fr: 'En cours', en: 'Generating' },
  'reports.statusScheduled': { fr: 'Planifié', en: 'Scheduled' },
  'reports.preview': { fr: 'Aperçu', en: 'Preview' },
  'reports.download': { fr: 'Télécharger', en: 'Download' },
  'reports.generateNewTitle': { fr: 'Générer un nouveau rapport', en: 'Generate New Report' },
  'reports.reportType': { fr: 'Type de rapport', en: 'Report Type' },
  'reports.selectType': { fr: 'Sélectionner le type', en: 'Select type' },
  'reports.period': { fr: 'Période', en: 'Period' },
  'reports.selectPeriod': { fr: 'Sélectionner la période', en: 'Select period' },
  'reports.today': { fr: 'Aujourd\'hui', en: 'Today' },
  'reports.customPeriod': { fr: 'Période personnalisée', en: 'Custom Period' },
  'reports.format': { fr: 'Format', en: 'Format' },
  'reports.generatingReport': { fr: 'Génération en cours...', en: 'Generating report...' },
  'reports.generate': { fr: 'Générer', en: 'Generate' },
  'reports.type': { fr: 'Type', en: 'Type' },
  'reports.status': { fr: 'Statut', en: 'Status' },
  'reports.generatedAt': { fr: 'Généré le', en: 'Generated at' },
  'reports.generatedBy': { fr: 'Généré par', en: 'Generated by' },
  'reports.fileSize': { fr: 'Taille fichier', en: 'File Size' },
  'reports.previewPlaceholder': { fr: 'Aperçu du rapport', en: 'Report Preview' },
  'reports.print': { fr: 'Imprimer', en: 'Print' },

  // Team Page
  'team.title': { fr: 'Équipe', en: 'Team' },
  'team.subtitle': { fr: 'Gérez les membres de votre équipe', en: 'Manage your team members' },
  'team.addMember': { fr: 'Ajouter un membre', en: 'Add Member' },
  'team.totalMembers': { fr: 'Total membres', en: 'Total Members' },
  'team.activeMembers': { fr: 'Membres actifs', en: 'Active Members' },
  'team.pathologists': { fr: 'Pathologistes', en: 'Pathologists' },
  'team.technicians': { fr: 'Techniciens', en: 'Technicians' },
  'team.membersTab': { fr: 'Membres', en: 'Members' },
  'team.activityTab': { fr: 'Activité', en: 'Activity' },
  'team.searchPlaceholder': { fr: 'Rechercher par nom, email...', en: 'Search by name, email...' },
  'team.filterRole': { fr: 'Rôle', en: 'Role' },
  'team.allRoles': { fr: 'Tous les rôles', en: 'All roles' },
  'team.filterStatus': { fr: 'Statut', en: 'Status' },
  'team.allStatuses': { fr: 'Tous les statuts', en: 'All statuses' },
  'team.roleAdmin': { fr: 'Administrateur', en: 'Administrator' },
  'team.rolePathologist': { fr: 'Pathologiste', en: 'Pathologist' },
  'team.roleTechnician': { fr: 'Technicien', en: 'Technician' },
  'team.roleClinician': { fr: 'Clinicien', en: 'Clinician' },
  'team.statusActive': { fr: 'Actif', en: 'Active' },
  'team.statusInactive': { fr: 'Inactif', en: 'Inactive' },
  'team.statusPending': { fr: 'En attente', en: 'Pending' },
  'team.membersList': { fr: 'Liste des membres', en: 'Members List' },
  'team.member': { fr: 'Membre', en: 'Member' },
  'team.role': { fr: 'Rôle', en: 'Role' },
  'team.status': { fr: 'Statut', en: 'Status' },
  'team.contact': { fr: 'Contact', en: 'Contact' },
  'team.casesHandled': { fr: 'Cas traités', en: 'Cases Handled' },
  'team.lastActive': { fr: 'Dernière activité', en: 'Last Active' },
  'team.joined': { fr: 'Rejoint le', en: 'Joined' },
  'team.avgTime': { fr: 'Moy', en: 'Avg' },
  'team.edit': { fr: 'Modifier', en: 'Edit' },
  'team.permissions': { fr: 'Permissions', en: 'Permissions' },
  'team.remove': { fr: 'Retirer', en: 'Remove' },
  'team.todayActivity': { fr: 'Activité du jour', en: 'Today\'s Activity' },
  'team.casesToday': { fr: 'cas aujourd\'hui', en: 'cases today' },
  'team.weeklySummary': { fr: 'Résumé hebdomadaire', en: 'Weekly Summary' },
  'team.casesWeek': { fr: 'cas cette semaine', en: 'cases this week' },
  'team.performanceOverview': { fr: 'Aperçu des performances', en: 'Performance Overview' },
  'team.casesTodayTotal': { fr: 'Cas aujourd\'hui', en: 'Cases Today' },
  'team.casesWeekTotal': { fr: 'Cas cette semaine', en: 'Cases This Week' },
  'team.avgResponseTime': { fr: 'Temps de réponse moy.', en: 'Avg Response Time' },
  'team.validationRate': { fr: 'Taux de validation', en: 'Validation Rate' },
  'team.addMemberTitle': { fr: 'Ajouter un membre', en: 'Add Team Member' },
  'team.firstName': { fr: 'Prénom', en: 'First Name' },
  'team.lastName': { fr: 'Nom', en: 'Last Name' },
  'team.email': { fr: 'Email', en: 'Email' },
  'team.phone': { fr: 'Téléphone', en: 'Phone' },
  'team.firstNamePlaceholder': { fr: 'Entrez le prénom', en: 'Enter first name' },
  'team.lastNamePlaceholder': { fr: 'Entrez le nom', en: 'Enter last name' },
  'team.emailPlaceholder': { fr: 'email@example.com', en: 'email@example.com' },
  'team.phonePlaceholder': { fr: '+225 00 00 00 00', en: '+225 00 00 00 00' },
  'team.selectRole': { fr: 'Sélectionner un rôle', en: 'Select a role' },
  'team.sendInvitation': { fr: 'Envoyer l\'invitation', en: 'Send Invitation' },
  'team.editMemberTitle': { fr: 'Modifier le membre', en: 'Edit Member' },
  'team.saveChanges': { fr: 'Enregistrer', en: 'Save Changes' },

  // Cases Page
  'cases.title': { fr: 'Cas', en: 'Cases' },
  'cases.subtitle': { fr: 'Gestion globale de tous les cas', en: 'Global management of all cases' },
  'cases.urgentPending': { fr: 'urgent(s) en attente', en: 'urgent pending' },
  'cases.export': { fr: 'Exporter', en: 'Export' },
  'cases.totalCases': { fr: 'Total cas', en: 'Total Cases' },
  'cases.pending': { fr: 'En attente', en: 'Pending' },
  'cases.analyzing': { fr: 'En analyse', en: 'Analyzing' },
  'cases.validated': { fr: 'Validés', en: 'Validated' },
  'cases.urgent': { fr: 'Urgents', en: 'Urgent' },
  'cases.listTab': { fr: 'Liste', en: 'List' },
  'cases.analyticsTab': { fr: 'Analytique', en: 'Analytics' },
  'cases.searchPlaceholder': { fr: 'Rechercher par ID, patient...', en: 'Search by ID, patient...' },
  'cases.filterStatus': { fr: 'Statut', en: 'Status' },
  'cases.allStatuses': { fr: 'Tous les statuts', en: 'All statuses' },
  'cases.statusDraft': { fr: 'Brouillon', en: 'Draft' },
  'cases.statusPending': { fr: 'En attente', en: 'Pending' },
  'cases.statusAnalyzing': { fr: 'En analyse', en: 'Analyzing' },
  'cases.statusValidated': { fr: 'Validé', en: 'Validated' },
  'cases.statusArchived': { fr: 'Archivé', en: 'Archived' },
  'cases.filterCenter': { fr: 'Centre', en: 'Center' },
  'cases.allCenters': { fr: 'Tous les centres', en: 'All centers' },
  'cases.casesList': { fr: 'Liste des cas', en: 'Cases List' },
  'cases.refresh': { fr: 'Actualiser', en: 'Refresh' },
  'cases.assignedTo': { fr: 'Assigné à', en: 'Assigned To' },
  'cases.viewDetails': { fr: 'Voir détails', en: 'View Details' },
  'cases.downloadReport': { fr: 'Télécharger rapport', en: 'Download Report' },
  'cases.archive': { fr: 'Archiver', en: 'Archive' },
  'cases.assignPathologist': { fr: 'Assigner pathologiste', en: 'Assign Pathologist' },
  'cases.cancel': { fr: 'Annuler le cas', en: 'Cancel Case' },
  'cases.trendChart': { fr: 'Tendance des cas', en: 'Cases Trend' },
  'cases.created': { fr: 'Créés', en: 'Created' },
  'cases.centerDistribution': { fr: 'Distribution par centre', en: 'Center Distribution' },
  'cases.summaryStats': { fr: 'Statistiques résumées', en: 'Summary Statistics' },
  'cases.totalThisYear': { fr: 'Total cette année', en: 'Total This Year' },
  'cases.validationRate': { fr: 'Taux de validation', en: 'Validation Rate' },
  'cases.avgTurnaround': { fr: 'Délai moyen', en: 'Avg Turnaround' },
  'cases.activeCenters': { fr: 'Centres actifs', en: 'Active Centers' },
  'cases.caseDetails': { fr: 'Détails du cas', en: 'Case Details' },
  'cases.createdBy': { fr: 'Créé par', en: 'Created By' },
  'cases.createdAt': { fr: 'Créé le', en: 'Created At' },
  'cases.validatedAt': { fr: 'Validé le', en: 'Validated At' },
  'cases.diagnosis': { fr: 'Diagnostic', en: 'Diagnosis' },

  // Activity Page
  'activity.title': { fr: 'Activité', en: 'Activity' },
  'activity.subtitle': { fr: 'Journal d\'activité et événements du système', en: 'Activity log and system events' },
  'activity.refresh': { fr: 'Actualiser', en: 'Refresh' },
  'activity.todayEvents': { fr: 'Événements aujourd\'hui', en: 'Events Today' },
  'activity.caseEvents': { fr: 'Événements cas', en: 'Case Events' },
  'activity.userEvents': { fr: 'Événements utilisateurs', en: 'User Events' },
  'activity.peakHour': { fr: 'Heure de pointe', en: 'Peak Hour' },
  'activity.timelineTab': { fr: 'Chronologie', en: 'Timeline' },
  'activity.analyticsTab': { fr: 'Analytique', en: 'Analytics' },
  'activity.searchPlaceholder': { fr: 'Rechercher dans l\'activité...', en: 'Search activity...' },
  'activity.filterType': { fr: 'Type', en: 'Type' },
  'activity.allTypes': { fr: 'Tous les types', en: 'All types' },
  'activity.filterPeriod': { fr: 'Période', en: 'Period' },
  'activity.today': { fr: 'Aujourd\'hui', en: 'Today' },
  'activity.yesterday': { fr: 'Hier', en: 'Yesterday' },
  'activity.thisWeek': { fr: 'Cette semaine', en: 'This Week' },
  'activity.thisMonth': { fr: 'Ce mois', en: 'This Month' },
  'activity.recentActivity': { fr: 'Activité récente', en: 'Recent Activity' },
  'activity.typeCaseCreated': { fr: 'Cas créé', en: 'Case Created' },
  'activity.typeCaseSubmitted': { fr: 'Cas soumis', en: 'Case Submitted' },
  'activity.typeCaseAnalyzed': { fr: 'Analyse', en: 'Analysis' },
  'activity.typeCaseValidated': { fr: 'Validé', en: 'Validated' },
  'activity.typeUserLogin': { fr: 'Connexion', en: 'Login' },
  'activity.typeUserLogout': { fr: 'Déconnexion', en: 'Logout' },
  'activity.typeUserCreated': { fr: 'Utilisateur créé', en: 'User Created' },
  'activity.typeSettings': { fr: 'Paramètres', en: 'Settings' },
  'activity.typeImageUploaded': { fr: 'Images', en: 'Images' },
  'activity.typeReportGenerated': { fr: 'Rapport', en: 'Report' },
  'activity.typeSecondOpinion': { fr: 'Second avis', en: 'Second Opinion' },
  'activity.roleSystem': { fr: 'Système', en: 'System' },
  'activity.hourlyDistribution': { fr: 'Distribution horaire', en: 'Hourly Distribution' },
  'activity.events': { fr: 'Événements', en: 'Events' },
  'activity.eventDistribution': { fr: 'Distribution par type', en: 'Event Distribution' },
  'activity.count': { fr: 'Nombre', en: 'Count' },
  'activity.summary': { fr: 'Résumé', en: 'Summary' },
  'activity.totalToday': { fr: 'Total aujourd\'hui', en: 'Total Today' },
  'activity.successRate': { fr: 'Taux de succès', en: 'Success Rate' },
  'activity.activeUsers': { fr: 'Utilisateurs actifs', en: 'Active Users' },
  'activity.activeCenters': { fr: 'Centres actifs', en: 'Active Centers' },

  // Settings Page
  'settings.title': { fr: 'Paramètres', en: 'Settings' },
  'settings.subtitle': { fr: 'Gérez votre profil, préférences et sécurité', en: 'Manage your profile, preferences and security' },
  'settings.profile': { fr: 'Profil', en: 'Profile' },
  'settings.notifications': { fr: 'Notifications', en: 'Notifications' },
  'settings.appearance': { fr: 'Apparence', en: 'Appearance' },
  'settings.security': { fr: 'Sécurité', en: 'Security' },
  'settings.profileInfo': { fr: 'Informations du profil', en: 'Profile Information' },
  'settings.profileInfoDesc': { fr: 'Mettez à jour vos informations personnelles', en: 'Update your personal information' },
  'settings.titleField': { fr: 'Titre', en: 'Title' },
  'settings.specialty': { fr: 'Spécialité', en: 'Specialty' },
  'settings.firstName': { fr: 'Prénom', en: 'First Name' },
  'settings.lastName': { fr: 'Nom', en: 'Last Name' },
  'settings.email': { fr: 'Email', en: 'Email' },
  'settings.phone': { fr: 'Téléphone', en: 'Phone' },
  'settings.center': { fr: 'Centre', en: 'Center' },
  'settings.save': { fr: 'Enregistrer', en: 'Save' },
  'settings.profileSaved': { fr: 'Profil enregistré avec succès', en: 'Profile saved successfully' },
  'settings.emailNotifications': { fr: 'Notifications par email', en: 'Email Notifications' },
  'settings.emailNotificationsDesc': { fr: 'Configurez les emails que vous souhaitez recevoir', en: 'Configure which emails you want to receive' },
  'settings.newCaseNotif': { fr: 'Nouveaux cas', en: 'New Cases' },
  'settings.newCaseNotifDesc': { fr: 'Recevoir un email lors de l\'attribution d\'un nouveau cas', en: 'Receive an email when a new case is assigned' },
  'settings.urgentNotif': { fr: 'Cas urgents', en: 'Urgent Cases' },
  'settings.urgentNotifDesc': { fr: 'Recevoir une alerte pour les cas marqués urgents', en: 'Receive alerts for cases marked as urgent' },
  'settings.resultsNotif': { fr: 'Résultats disponibles', en: 'Results Available' },
  'settings.resultsNotifDesc': { fr: 'Notification quand un résultat est prêt', en: 'Notification when a result is ready' },
  'settings.weeklyReport': { fr: 'Rapport hebdomadaire', en: 'Weekly Report' },
  'settings.weeklyReportDesc': { fr: 'Recevoir un résumé de l\'activité chaque semaine', en: 'Receive a weekly activity summary' },
  'settings.pushNotifications': { fr: 'Notifications push', en: 'Push Notifications' },
  'settings.pushNotificationsDesc': { fr: 'Notifications en temps réel sur votre appareil', en: 'Real-time notifications on your device' },
  'settings.pushNewCase': { fr: 'Nouveau cas assigné', en: 'New Case Assigned' },
  'settings.pushNewCaseDesc': { fr: 'Alerte instantanée pour les nouveaux cas', en: 'Instant alert for new cases' },
  'settings.pushUrgent': { fr: 'Alertes urgentes', en: 'Urgent Alerts' },
  'settings.pushUrgentDesc': { fr: 'Notifications prioritaires pour les urgences', en: 'Priority notifications for emergencies' },
  'settings.pushSecondOpinion': { fr: 'Demandes de second avis', en: 'Second Opinion Requests' },
  'settings.pushSecondOpinionDesc': { fr: 'Notification lors d\'une demande de consultation', en: 'Notification when a consultation is requested' },
  'settings.sound': { fr: 'Sons', en: 'Sounds' },
  'settings.soundDesc': { fr: 'Activer les sons de notification', en: 'Enable notification sounds' },
  'settings.notificationsSaved': { fr: 'Préférences de notification enregistrées', en: 'Notification preferences saved' },
  'settings.themeSettings': { fr: 'Thème et affichage', en: 'Theme and Display' },
  'settings.themeSettingsDesc': { fr: 'Personnalisez l\'apparence de l\'application', en: 'Customize the application appearance' },
  'settings.theme': { fr: 'Thème', en: 'Theme' },
  'settings.lightMode': { fr: 'Clair', en: 'Light' },
  'settings.darkMode': { fr: 'Sombre', en: 'Dark' },
  'settings.systemMode': { fr: 'Système', en: 'System' },
  'settings.language': { fr: 'Langue', en: 'Language' },
  'settings.fontSize': { fr: 'Taille de police', en: 'Font Size' },
  'settings.fontSmall': { fr: 'Petite', en: 'Small' },
  'settings.fontMedium': { fr: 'Moyenne', en: 'Medium' },
  'settings.fontLarge': { fr: 'Grande', en: 'Large' },
  'settings.compactMode': { fr: 'Mode compact', en: 'Compact Mode' },
  'settings.compactModeDesc': { fr: 'Réduire l\'espacement pour afficher plus de contenu', en: 'Reduce spacing to display more content' },
  'settings.highContrast': { fr: 'Contraste élevé', en: 'High Contrast' },
  'settings.highContrastDesc': { fr: 'Améliorer la lisibilité avec des couleurs plus contrastées', en: 'Improve readability with higher contrast colors' },
  'settings.appearanceSaved': { fr: 'Préférences d\'apparence enregistrées', en: 'Appearance preferences saved' },
  'settings.changePassword': { fr: 'Changer le mot de passe', en: 'Change Password' },
  'settings.changePasswordDesc': { fr: 'Mettez à jour votre mot de passe régulièrement pour plus de sécurité', en: 'Update your password regularly for better security' },
  'settings.currentPassword': { fr: 'Mot de passe actuel', en: 'Current Password' },
  'settings.newPassword': { fr: 'Nouveau mot de passe', en: 'New Password' },
  'settings.confirmPassword': { fr: 'Confirmer le mot de passe', en: 'Confirm Password' },
  'settings.updatePassword': { fr: 'Mettre à jour', en: 'Update' },
  'settings.passwordMismatch': { fr: 'Les mots de passe ne correspondent pas', en: 'Passwords do not match' },
  'settings.passwordTooShort': { fr: 'Le mot de passe doit contenir au moins 8 caractères', en: 'Password must be at least 8 characters' },
  'settings.passwordChanged': { fr: 'Mot de passe modifié avec succès', en: 'Password changed successfully' },
  'settings.twoFactor': { fr: 'Authentification à deux facteurs', en: 'Two-Factor Authentication' },
  'settings.twoFactorDesc': { fr: 'Ajoutez une couche de sécurité supplémentaire à votre compte', en: 'Add an extra layer of security to your account' },
  'settings.2faEnabled': { fr: 'Authentification à deux facteurs activée', en: 'Two-factor authentication enabled' },
  'settings.2faDisabled': { fr: 'Authentification à deux facteurs désactivée', en: 'Two-factor authentication disabled' },
  'settings.2faActive': { fr: 'Activée', en: 'Enabled' },
  'settings.2faInactive': { fr: 'Désactivée', en: 'Disabled' },
  'settings.2faActiveDesc': { fr: 'Votre compte est protégé par 2FA', en: 'Your account is protected by 2FA' },
  'settings.2faInactiveDesc': { fr: 'Activez 2FA pour plus de sécurité', en: 'Enable 2FA for better security' },
  'settings.enable': { fr: 'Activer', en: 'Enable' },
  'settings.disable': { fr: 'Désactiver', en: 'Disable' },
  'settings.sessionSettings': { fr: 'Session', en: 'Session' },
  'settings.sessionSettingsDesc': { fr: 'Gérez la durée de votre session', en: 'Manage your session duration' },
  'settings.sessionTimeout': { fr: 'Délai d\'expiration', en: 'Session Timeout' },
  'settings.sessionTimeoutDesc': { fr: 'Durée d\'inactivité avant déconnexion automatique', en: 'Inactivity duration before automatic logout' },
  'settings.minutes': { fr: 'minutes', en: 'minutes' },
  'settings.hour': { fr: 'heure', en: 'hour' },
  'settings.hours': { fr: 'heures', en: 'hours' },
  'settings.dangerZone': { fr: 'Zone dangereuse', en: 'Danger Zone' },
  'settings.dangerZoneDesc': { fr: 'Actions irréversibles sur votre compte', en: 'Irreversible actions on your account' },
  'settings.deleteAccount': { fr: 'Supprimer mon compte', en: 'Delete My Account' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = useCallback((key: string): string => {
    const translation = translations[key];
    if (!translation) {
      console.warn(`Translation missing for key: ${key}`);
      return key;
    }
    return translation[language];
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
